version: '3'
services:
  backend:
    image: myappback
    ports:
      - "8080:5000"
    environment:
      - CURRENT_ENVIRONMENT=production
    volumes:
      - /var/log:/logs

  frontend:
    image: myappfront
    ports:
      - "8081:80"
    environment:
      - WS_BACK_URL=http://localhost:8080/